Create gssearch.py
This-is-XiaoDeng/XDbot2 pull request #70
Opened 2023-03-04 07:38 UTC by YifanZhuZhu

yf制作西风驿站攻略查询

2023-03-04 08:08 UTC, xxtg666 commented
冗余代码过多，请使用dict

2023-03-04 08:08 UTC, YifanZhuZhu commented
6

2023-03-04 08:08 UTC, This-is-XiaoDeng requested changes

2023-03-04 08:08 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +gssearch = on_command("gssearch", aliases={"原神角色查询", "西风驿站"}, priority=10)
没搞优先级的必要

```suggestion
gssearch = on_command("gssearch", aliases={"原神角色查询", "西风驿站"})
```

2023-03-04 08:08 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +    if str(message) == "风主":
sw不是让你搞dict吗（？

2023-03-04 08:08 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +        pic = MessageSegment.image(requests.get("https://upload-bbs.miyoushe.com/upload/2022/05/20/74019947/374c90a6ef78d74888e797c1b6624723_3616634552285922830.png").content)
6，你是懂异步的

2023-03-04 08:08 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +    msg = await vocaloid.send(msgb)
我咋记得matcher.send获取不到message_id

2023-03-04 08:08 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +    await asyncio.sleep(114)
这么久你撤回有什么意义（

2023-03-04 08:09 UTC, YifanZhuZhu commented on src/plugins/Core/plugins/gssearch.py
> +    msg = await vocaloid.send(msgb)
可以的

2023-03-04 08:09 UTC, YifanZhuZhu commented on src/plugins/Core/plugins/gssearch.py
> +    msg = await vocaloid.send(msgb)
我等等

2023-03-04 08:10 UTC, YifanZhuZhu commented on src/plugins/Core/plugins/gssearch.py
> +    msg = await vocaloid.send(msgb)
草，666

2023-03-04 08:10 UTC, YifanZhuZhu commented on src/plugins/Core/plugins/gssearch.py
> +    msg = await vocaloid.send(msgb)
套的之前的文件

2023-03-04 08:10 UTC, YifanZhuZhu commented on src/plugins/Core/plugins/gssearch.py
> +    msg = await vocaloid.send(msgb)
改改（）

2023-03-04 08:31 UTC, This-is-XiaoDeng requested changes

2023-03-04 08:31 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +import requests
请使用async的httpx

2023-03-04 08:31 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +# [HELPEND]
无效的帮助文本

2023-03-04 08:32 UTC, YifanZhuZhu commented on src/plugins/Core/plugins/gssearch.py
> +# [HELPEND]
？6

2023-03-04 08:32 UTC, YifanZhuZhu commented on src/plugins/Core/plugins/gssearch.py
> +import requests
azz？

2023-03-04 13:10 UTC, This-is-XiaoDeng requested changes
1. HELP文本依旧无效
2. 请使用async发起网络请求

麻烦改下，就这两点=m=

2023-03-04 13:10 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +# Usage: gssearch <角色名>：查询角色的攻略
```suggestion
# Usage: gssearch <角色名>：查询角色的攻略
# [HELPEND]
```

2023-03-04 13:14 UTC, This-is-XiaoDeng commented
我先给你merge了我自己改吧（恼

2023-03-05 03:23 UTC, XieXiLin3 reviewed
有待测试。

2023-03-05 03:25 UTC, This-is-XiaoDeng requested changes

2023-03-05 03:25 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +# Usage: gssearch <角色名>：查询原神角色<角色名>的攻略
```suggestion
# Usage: gssearch <角色名>
# [HELPEND]
```

2023-03-05 03:45 UTC, This-is-XiaoDeng requested changes

2023-03-05 03:45 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +# Usage: gssearch <角色名>
```suggestion
# Usage: gssearch <角色名>
# [HELPEND]
```

2023-03-05 03:48 UTC, This-is-XiaoDeng reviewed
你加油.jpg

2023-03-05 03:52 UTC, YifanZhuZhu commented
终于。

2023-03-05 03:53 UTC, This-is-XiaoDeng requested changes

2023-03-05 03:53 UTC, This-is-XiaoDeng commented on src/plugins/Core/plugins/gssearch.py
> +    msg = await gssearch.send(Message("[CQ:image, url="+urls[str(message)]+"]")+f"攻略制作:猫冬 https://www.miyoushe.com/ys/accountCenter/postList?id=74019947")
```suggestion
    msg = await gssearch.send(Message(f"[CQ:image, url={urls[str(message)]}]攻略制作: 猫冬\nhttps://www.miyoushe.com/ys/accountCenter/postList?id=74019947"))
```

2023-03-05 03:55 UTC, This-is-XiaoDeng approved these changes

2023-03-05 03:56 UTC, This-is-XiaoDeng commented
等下更新完出bug了你记得修下，我会再issue at你的（（

2023-03-05 03:56 UTC, merged